version: '3.8'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=dan
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres:
